### ISSUE TITLE
UPDATE THE ACTUAL WEBSITE ON A REGULAR BASIS

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#101]
This is ABSURD. The site repeatedly goes MONTHS out of date. This has been an issue since LAST YEAR. If I can't have push access to the server then I will end up setting up my own kovri domain. There's no point in having a website if it's serving misinformation. People are making the contributions but the actual site is not reflecting them. https://getmonero.org doesn't receive this kind of neglect, what gives?

**Comment by anonimal** [comment]
#79

**Comment by el00ruobuob** [comment]
Totally agree here.
Please @fluffypony / @luigi1111 or any relevant core team member give @anonimal access to the server so he could rebuild the site when needed.

**Comment by fluffypony** [comment]
I personally manage getmonero.org, that’s why it doesn’t have this problem. I have no idea where the Kovri site is even hosted.

**Comment by el00ruobuob** [comment]
Sorry for unnecessarily involving you then. :flushed:

**Comment by anonimal** [comment]
>I have no idea where the Kovri site is even hosted.

getkovri.org is in the hands of a non-core team member and non-kovri developer?...

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
