### ISSUE TITLE
Video on the index not working for chrome 67.0.3396.99

### ISSUE THREAD

**Issue by Onefox** [monero-project/kovri-site#111]
Is it only me or is the video on the index not working for everybody with chrome 67.0.3396.99?

The [link ](https://getkovri.org/img/kovri-video.mp4) is correct and in Firefox it will work.

Edit: using win 8.1 pro 9600

**Comment by anonimal** [comment]
Referencing https://github.com/monero-project/kovri-site/issues/70#issuecomment-397512516 (chromium 67.0.3396.99).

**Comment by Josexv1** [comment]
Can reproduce this issue, the video starts but stops after 0.1s or doesn't start at all, then after a few tries it breaks.

Chrome: Version 67.0.3396.99 (Official Build) (64-bit) & Version 68.0.3440.75 (Official Build) (64-bit)
 
![screenshot 39](https://user-images.githubusercontent.com/12077848/43271169-d646de6a-90c4-11e8-8654-513ca9306e6d.png)

**Comment by Josexv1** [comment]
After extensive testing, i found that i can't play some types of .mp4 files.

|SOURCE|TYPE|OPTIONS|Result|
|---|---|---|---|
Local|mp4|None|FAIL|
Local|webm|None|FAIL|
Local|mp4|poster, type, height, width|FAIL|
Local|mp4|autoplay|FAIL|
Web|mp4|default(controls, source, type)| OK|
Web|webm|default(controls, source, type)|FAIL|
Web|mp4|none|FAIL|
Web|mp4|multiple sources|FAIL

I didn't see much of a change using diferent options or multiple sources, the video won't load the first time, and it will look broken without being able to click _play_
The thing is that some mp4 files **can** be reproduced, others will fail to load.
Also doing some tests with the Chrome DevTools, i found that if you do a performance test, the video that previously didn't load will load just fine.

**FIX:** 
- We can try to hack Jekyll to see if there's something we can do
- We can use a Jekyll video plugin
- We can try to use another open format for the video, like MKV _(didn't test it)_

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
