### ISSUE TITLE
Tighten writing up in docs

### ISSUE THREAD

**Issue by rehrar** [monero-project/kovri-site#13]
It would be good to go through the docs and tighten up the writing. There are a couple of errors here and there, as well as perhaps some places that can be clarified a bit.

In short, a thorough editing of the existing documentation would benefit the website. There's also the idea of making it a bit more readable at the expense of increasing verbosity, as I usually do with my documentation, but for something like Kovri I don't think it'd be as beneficial as in Monero.

**Comment by rehrar** [comment]
Perhaps a good compromise would be a 'Quick Start' guide that just outlines the steps as quick bullet points, and an in-depth guide for noobs who still want to use the software. Thoughts?

**Comment by anonimal** [comment]
This issue should be in https://github.com/monero-project/kovri-docs.

**Comment by anonimal** [comment]
Moved to https://github.com/monero-project/kovri-docs/issues/3.
