### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rehrar** [monero-project/kovri-site#15]
We currently have five translations available (English, Spanish, Russian, French, and Italian). Not all of these are being actively translated. Identifying individuals who can help and translate is needed.

As well, gauging interest in volunteer translators to help to translate the website into other languages is extremely important as well.

This issue should remain open and anyone who wishes to see a language added should comment below. Adding a language is not in the current version of the written Kovri documentation so I will have to do it for now. I will add the instructions to add another language soon.

**Comment by Josexv1** [comment]
I was planning to make a `rake` file to create new translations and/or new pages to the site. I think that should help it, i second leaving this issue open as a medium to manage new translations

**Comment by erciccione** [comment]
Hopefully i can finish the missing italian translations next week. We also have some volunteers for the translations in french and russian (see [here](https://www.reddit.com/r/Monero/comments/6kjuzh/monero_translations_updates_and_amazingness/)). Instructions will be very appraciated :)

**Comment by Dridou** [comment]
I'm a native french speaker and I can translate anything you need to in French, you only need to tell me what to translate =)

**Comment by anonimal** [comment]
@Dridou @Vanchesss and @MoroccanMalinois have done French + Russian work in https://github.com/monero-project/kovri-site/pull/16 https://github.com/monero-project/kovri-site/pull/17.

I think we need to start focusing on moving doc translations to [kovri-docs](https://github.com/monero-project/kovri-docs) a.s.a.p as specified in #6.

**Comment by anonimal** [comment]
#6 was resolved and all translations have been moved to https://github.com/monero-project/kovri-docs (translation work can continue within that repo).
