### ISSUE TITLE
No such file or directory @ dir_chdir

### ISSUE THREAD

**Issue by danrmiller** [monero-project/kovri-site#27]
commit d23cd74 is the last version that builds without errors under jekyll 3.0.1.

Each subsequent commit gives these errors:

Building site for default language: "en" to: /var/www/kovri/kovri-site/kovri.i2p/_site
  Liquid Exception: No such file or directory @ dir_chdir - /var/www/kovri/kovri-site/kovri.i2p/_i18n/en in doc/acknowledgements.html
Building site for language: "es" to: /var/www/kovri/kovri-site/kovri.i2p/_site/es
  Liquid Exception: No such file or directory @ dir_chdir - /var/www/kovri/kovri-site/kovri.i2p/_i18n/es in doc/acknowledgements.html
Building site for language: "ru" to: /var/www/kovri/kovri-site/kovri.i2p/_site/ru
  Liquid Exception: No such file or directory @ dir_chdir - /var/www/kovri/kovri-site/kovri.i2p/_i18n/ru in doc/acknowledgements.html
Building site for language: "fr" to: /var/www/kovri/kovri-site/kovri.i2p/_site/fr
  Liquid Exception: No such file or directory @ dir_chdir - /var/www/kovri/kovri-site/kovri.i2p/_i18n/fr in doc/acknowledgements.html
Building site for language: "it" to: /var/www/kovri/kovri-site/kovri.i2p/_site/it
  Liquid Exception: No such file or directory @ dir_chdir - /var/www/kovri/kovri-site/kovri.i2p/_i18n/it in doc/acknowledgements.html
Build complete

**Comment by anonimal** [comment]
Since 109af457ef39118ef6fa122ae81dd05cce399e23, this repo now requires a recursive pull or `git submodule init && git submodule update`. Also noted in https://github.com/monero-project/kovri-site#cloning.

Does that resolve this issue?

**Comment by danrmiller** [comment]
Thanks, the build works now. These are the errors from jekyll serve:

 Auto-regeneration: enabled for '/var/www/kovri/kovri-site/kovri.i2p'
Configuration file: /var/www/kovri/kovri-site/kovri.i2p/_config.yml
        ** ERROR: directory is already being watched! **

        Directory: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/es

        is already begin watched through: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/es

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/it

        is already begin watched through: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/it

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/ru

        is already begin watched through: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/ru

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/en

        is already begin watched through: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/en

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/fr

        is already begin watched through: /var/www/kovri/kovri-site/kovri.i2p/kovri-docs/i18n/fr

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors

**Comment by anonimal** [comment]
jekyll might be seeing things as being recursively symlinked. Moving kovri-docs to the root directory fixes this issue.

**Comment by anonimal** [comment]
Confirmed after reading https://github.com/guard/listen/wiki/Duplicate-directory-errors.
