### ISSUE TITLE
Provide X-I2P header response on check.kovri.i2p 

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#4]
From https://github.com/monero-project/meta/issues/45:

>From https://github.com/monero-project/kovri/issues/540:
>>HTTP client tunnel output to file will also ease sharing of whitelisted addresses for server tunnels

>~~Instead~~ In addition to a file, we can implement on check.kovri.i2p to provide a header response for HTTP client tunnels *without* persistent keys, similar to what stats.i2p/cgi-bin/mydest is doing (see tunnels config documentation for details).

>This is trivial to implement with PHP. Ticketing for housekeeping.

**Comment by serhack** [comment]
Hello,
This is the code for request all headers

```
<?php
$headers = apache_request_headers();

foreach ($headers as $header => $value) {
    echo "$header: $value <br />\n";
}
```

What header do you want?

**Comment by anonimal** [comment]
Hi @serhack.

The workhorse (not a big horse) part of this issue is implementing server tunnel appending of headers `X-I2P-DestHash:` `X-I2P-DestB32:` and `X-I2P-DestB64:` but this will be done via the kovri repo. All that needs to be done here on kovri-site is what you pasted (including `?>`) and also doing something style-wise so it's not just a blank page with HTTP headers. Maybe that's something you and @rehrar can work together on.
