### ISSUE TITLE
Code blocks not displayed correctly

### ISSUE THREAD

**Issue by rodolfo912** [monero-project/kovri-site#49]
- This is relevant for the sites building, user_guide and style and occured on all OS browser combinations I checked.
- The code blocks, which are displayed correctly in the md-files on GitHub, are off on the website, e.g. "bash" is displayed. See, for example, this screenshot from bulding:
![getkovri_building](https://user-images.githubusercontent.com/32744922/32772237-876e5690-c925-11e7-93de-43bf9808ba98.png)
- When running Jekyll locally, the first line of the code blocks is intended, otherwise it is fine. See this screenshot from localhost for the same parts as in the above screenshot:
![getkovri_building_local](https://user-images.githubusercontent.com/32744922/32772386-fd9d59ba-c925-11e7-8a12-e12967e34cc6.png)

**Comment by rehrar** [comment]
This seems to be resolved with the current version of the site. @rodolfo912 can you confirm?

**Comment by rodolfo912** [comment]
@rehrar Yes.
