### ISSUE TITLE
Create Doxygen Section

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#5]
Similar to https://cryptopp.com/docs/ref/, we currently have Doxygen in the build options of the kovri repo. Streamlining and fine-tuning the config to work with kovri-site would be ideal.

**Comment by rehrar** [comment]
Doxygen section is now up [here](https://getkovri.org/doxygen).

**Comment by anonimal** [comment]
Thank you @rehrar !!! 🎉 🎈
