### ISSUE TITLE
Add possibility to use an 'untranslated' snippet

### ISSUE THREAD

**Issue by erciccione** [monero-project/kovri-site#64]
for untranslated pages, as it is for getmonero.org

**Comment by rehrar** [comment]
I can go ahead and set up the same thing, although with @el00ruobuob's recent versioning and stuff, it'd be helpful to get him involved if we wanted to use the same docs versioning system as is in getmonero.org

**Comment by el00ruobuob** [comment]
Sure, i can give it a look this week.

**Comment by el00ruobuob** [comment]
I don't understand how it works here.
On getmonero, there is the root ressource folder with front matter. It's where i place the "latest version" for guide versioning. But here, no such files with front matter. Could you clarify @rehrar ?

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
