### ISSUE TITLE
IE11 index display issue

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/kovri-site#68]
Index page is displaying incorrectly on IE11
"Downloads" & "Blog" Section are standing vertically instead of horizontally.

![image](https://user-images.githubusercontent.com/37215310/41196689-71042b6c-6c47-11e8-8fb8-30e46f043c70.png)

**Comment by rehrar** [comment]
Internet explorer, why?

**Comment by Josexv1** [comment]
IE11 is not fully supported by MS. [Read here.](https://social.technet.microsoft.com/Forums/en-US/de3bedbb-1d8f-4d6a-9da0-0eb369ce78f6/is-internet-explorer-11-still-supported-by-microsoft?forum=win10itprogeneral)

**Will Internet Explorer 11 continue to receive updates?**
_- The latest features and platform updates will only be available in Microsoft Edge. We will continue to deliver security updates to Internet Explorer 11 through its supported lifespan. To ensure consistent behavior across Windows versions, we will evaluate Internet Explorer 11 bugs for servicing on a case by case basis._

There's no reason to support IEx

**Comment by el00ruobuob** [comment]
It's still the default on Windows 8 which is still supported yet. I'm just saying as IE11 is one of my testing browsers on my testing platform.
If you says that I should not test anything on IE11, that's fine. Less tests for me then.

**Comment by el00ruobuob** [comment]
Btw isn't IE11 the best browser ever? (Apart for any other browsers)

**Comment by el00ruobuob** [comment]
So, do we say we do not support IE11 and i remove IE11 from my testing browsers?

**Comment by anonimal** [comment]
If I were engineering this site I would redirect all IE requests to mozilla :smirk:

**Comment by rehrar** [comment]
I say that we remove IE from support period. It's a pain to work with on all fronts.

**Comment by el00ruobuob** [comment]
IE11 not supported any longer.
