### ISSUE TITLE
Contributing page relocalized

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/kovri-site#69]
Contributing page has not been relocalized in #66 
Is there a technical reason for this? Or has it been just forgotten?

If you want me to get into it @rehrar, just ask, i could do this within 1 week i believe.

**Comment by anonimal** [comment]
What I do know is that we've condensed the writing into a user guide and developer guide. As to how that plays out on the website, that's TBD.

**Comment by el00ruobuob** [comment]
if there is no need for it in the actual form, maybe better removing it? or keeping at the moment not to rebuild the CSS and replace with something else later?

**Comment by el00ruobuob** [comment]
@rehrar do you think this page will be kept for #79 ? Does @erciccione team need to translate it in the original md file to solve #83 ?

**Comment by anonimal** [comment]
Referencing #79.

**Comment by rehrar** [comment]
Contributing page was relocalized in #87
