### ISSUE TITLE
getkovri.org video not loading in Tor Browser

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#70]
![tbb_getkovri](https://user-images.githubusercontent.com/12156341/41387079-8db5b5de-6f74-11e8-85b6-7fc4ce9766a7.png)

**Comment by anonimal** [comment]
May affect other browsers too. I cannot reproduce on vanilla firefox.

**Comment by ordtrogen** [comment]
You're using too many bits! Just remove half of them :-)

![image](https://user-images.githubusercontent.com/15184875/41401389-048ef7ec-6fc0-11e8-8d28-75cb74f5cdd4.png)

**Comment by Josexv1** [comment]
Tested and everything was fine. Also tested Firefox 52, and everything was fine.

**Comment by anonimal** [comment]
I have installed a fresh TBB in a VM and can reproduce this issue (js enabled/disabled):
![tbb_getkovri org](https://user-images.githubusercontent.com/12156341/41450240-de9e91a0-7055-11e8-8cb4-19f79c102575.png)

mp4 is supported in-browser, I watch mp4s all the time, but:

![tbb2_getkovri org](https://user-images.githubusercontent.com/12156341/41450298-354d5b26-7056-11e8-9070-f3932edca86b.png)

Also, proxying chromium (js enabled) produces a similar issue:

![chromium_getkovri org](https://user-images.githubusercontent.com/12156341/41450302-43209772-7056-11e8-8c62-6fff3e560bed.png)

**Comment by anonimal** [comment]
Referencing #79

**Comment by Josexv1** [comment]
This is really weird, i can't seem to reproduce this issue. 

OS | 32 | 64
------------ | ------------- | -------------
Windows 10 latest | OK | OK
Ubuntu16 | OK | OK
Kali Linux Rolling | OK | OK

![screenshot 33](https://user-images.githubusercontent.com/12077848/42333370-8ec1b1c8-8048-11e8-929c-4c8a61856513.png)

I did test, blocking JS and setting strict security rules and everything was just fine.
What is your test env?

**Comment by anonimal** [comment]
Note: I'm not using AUR, I've pulled directly from the torproject website. The AUR doesn't show any patches. If this is a torproject / Arch issue then I or someone else on the planet should report the issue. If there's truly nothing that can be done on our end then let's close the issue.

**Comment by Josexv1** [comment]
Can you test in a VM with another OS?
I prefer to wait for someone else to do some tests too before we close this issue. I will download Arch to do a livecd test when i can.

**Comment by anonimal** [comment]
>Can you test in a VM with another OS?

I'm pretty busy at the moment, I don't think I will have time before defcon.

>I will download Arch to do a livecd test when i can.

Thank you!

**Comment by coneiric** [comment]
Was able to view the video through Tor browser. Needed to click the media button (Tor's safety feature to stop auto-play), and it loaded fine after that.

**Comment by anonimal** [comment]
I can still reproduce this issue.

**Comment by anonimal** [comment]
Reopen if needed.

**Comment by anonimal** [comment]
#111 means this issue should be reopened.

**Comment by Josexv1** [comment]
I got a few guys test in Arch Linux, and indeed the video isn't loading.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
