### ISSUE TITLE
Ambiguity in build instructions

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/kovri-site#71]
1. Should there be a space before the number of CPUs or not?

2. Are those backticks/backquotes, or should they be normal single quotation marks? AFAIK the backtick has a special function in many shells, but it doesn't look like that's what's intended here

![image](https://user-images.githubusercontent.com/15184875/41401181-6c53f856-6fbf-11e8-9a49-1cb00db7964c.png)

**Comment by erciccione** [comment]
1. AFAIK it makes no difference
2. I think here backquotes are used because for consistency with the markdown structure (since all code should go between backquotes) and they are not shell instructions

**Comment by Josexv1** [comment]
1. I think it's the same with or without space, but it's commonly used together ie: `make -j8` And the numbers is the available CPU cores +1 or +2.
2. It's commonly accepted to use `` to represent code.

**Comment by anonimal** [comment]
@ordtrogen The build instructions have changed. Build instructions are now in the kovri README now. We'll need translations though, just like in https://github.com/monero-project/kovri/pull/906.

kovri-site should adjust to these changes a.s.a.p so we save time for translators.

**Comment by anonimal** [comment]
Referencing #79

**Comment by anonimal** [comment]
Resolved, at least for non-Russian languages. Russian changes to kovri-docs will happen when someone comes along to do them.
