### ISSUE TITLE
Kovri-docs FAQ

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/kovri-site#72]
Hi guys,

FAQ ~~and acknowledgements~~ file ~~are~~ is not used on getkovri. Or ~~are they~~ is it and am i blind?
Is it something someone (i mean @rehrar) is working on? A mistake? Or on purpose?

++

**Comment by Josexv1** [comment]
Acknowledgements  is at the bottom... The FAQ is not there AFAIK.

**Comment by el00ruobuob** [comment]
@rehrar do you think this page will be kept for #79 ? Does @erciccione team need to translate it in kovri-docs to solve #83 ?

**Comment by anonimal** [comment]
Referencing #79

**Comment by anonimal** [comment]
Resolved in https://github.com/monero-project/kovri-site/pull/97.
