### ISSUE TITLE
Use the kovri-docs submodule

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#73]
The whole purpose of the submodule was to avoid things like https://github.com/monero-project/kovri-site/tree/master/kovri.i2p/_i18n/en as introduced in af8c2bf4216b92f03e92c6c0b0cb78f045b02d08.

kovri-site should be generating content on the fly based on whatever is in the kovri-docs submodule, not hardcoded like what has happened.

**Comment by rehrar** [comment]
I made a link from this place to the submodule. :/ Perhaps I screwed it up somehow, as often happens. Looking into it.

**Comment by rehrar** [comment]
Yes sir, on it right now.

**Comment by anonimal** [comment]
Resolved in https://github.com/monero-project/kovri-site/pull/88.

**Comment by anonimal** [comment]
Referencing #79
