### ISSUE TITLE
Add Jekyll building instructions in README

### ISSUE THREAD

**Issue by Josexv1** [monero-project/kovri-site#74]
Would be very convenient to have clear instructions to serve a local copy of the site for new devs and translators in the README.

**Comment by anonimal** [comment]
@Josexv1 something like https://github.com/monero-project/kovri-site/pull/75?

**Comment by Josexv1** [comment]
More technical, for exmaple i had to mod the _config.yml because my jekyll said most of the stuff was deprecated.
1. `git clone --recursive https://github.com/monero-project/kovri-site`
2. `cd kovri-site/kovri.i2p/`
3.  edit `_config.yml`, change `plugins` to `plugins_dir`
4.  add to `_config.yml`
```# Gems
gems: [jekyll-paginate, jekyll-multiple-languages-plugin]
```
5. `Jekyll serve --incremental`
6. Start translating or editing the site, to view the live changes.
7. More details if needed.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
