### ISSUE TITLE
Downloads section for official releases

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#78]
Like getmonero.org/downloads. Or shall we simply redirect to github?

**Comment by Josexv1** [comment]
If we can setup the builds before the launch let's do it as getmonero.org, but if we want to focus on other things we can put links to github releases meanwhile.

**Comment by anonimal** [comment]
Referencing #79

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
