### ISSUE TITLE
Kovri-docs developer notes section

### ISSUE THREAD

**Issue by coneiric** [monero-project/kovri-site#80]
Discussed in Kovri meeting on 28-06-2018, a section of the site for developer notes/cheatsheets would be helpful for quick reference.

The Java I2P documentation is somewhat disperse, and having a cheatsheet for all related data structures would be easier to make sense of.

Here is an example for the `RouterInfo` data structure: [router_info_size.md](https://gist.github.com/coneiric/a2bc40172cd7a5465ba8e2b527b1c0c5)

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
