### ISSUE TITLE
Update all existent languages

### ISSUE THREAD

**Issue by erciccione** [monero-project/kovri-site#83]
Ok folks, the alpha release is close and we have to translate all the missing parts of the existent translations in this repository.

Instructions on how to update a translation can be found in [the related wiki section on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/translating-kovri-website), but basically, the files who need to be translated are located in the [_i18n folder](https://github.com/monero-project/kovri-site/tree/master/kovri.i2p/_i18n) in this repository. Just make sure the `.yml` file related to your language is updated along with all the content of the folder.

- [ ] **Spanish**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/310
- [x] **German**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/307
- [ ] **Russian**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/309
- [x] **French**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/306
- [ ] **Italian**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/308
- [ ] **Danish**
Task on Taiga: https://taiga.getmonero.org/project/erciccione-monero-localization/task/305

**Comment by el00ruobuob** [comment]
I have done the yml. I am updating kovri-docs (work in progress) and will publish the changes in a week or two.

**Comment by erciccione** [comment]
@el00ruobuob thanks, but keep in mind that this issue is about the content of kovri-site not kovri-docs and also the content of the `fr` folder should be translated

**Comment by Josexv1** [comment]
I will keep this comment updated with my progress on Spanish kovri-site asi i have it [assigned on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/us/50)

- [x] modified:   kovri.i2p/_data/lang/es/navigation.yml
- [x] modified:   kovri.i2p/_i18n/es.yml
- [x] modified:   kovri.i2p/_i18n/es/acknowledgements.md
- [x] modified:   kovri.i2p/_i18n/es/building.md
- [x] modified:   kovri.i2p/_i18n/es/contributing-docs.md
- [x] modified:   kovri.i2p/_i18n/es/contributing.md
- [x] modified:   kovri.i2p/_i18n/es/faq.md
- [x] modified:   kovri.i2p/_i18n/es/index.md
- [ ] unchanged:  kovri.i2p/_i18n/es/intro.md
- [ ] unchanged: kovri.i2p/_i18n/es/legal.md
- [ ] unchanged: kovri.i2p/_i18n/es/quality.md
- [ ] unchanged: kovri.i2p/_i18n/es/style.md
- [ ] unchanged: kovri.i2p/_i18n/es/user-guide.md

The rest will updated in the following days. Only 5 files left.
I took #65 as my base to translate, as we approved the changes, and later we can talk about the right words to use in confusing wordings. If anyone wants to see the files, comment and i will push to my fork.

**Comment by erciccione** [comment]
Thanks @Josexv1 great to have a tracker :) Btw i see you have the whole userstory assigend at the moment, not the task, that can be confusing. I suggest you to "watch" the userstory on taiga, not to assign it to yourself. I'm removing the "assigned to" from the userstory and moving it to the task.

**Comment by Josexv1** [comment]
Sure, Taiga has a lot of stuff, so sometimes is confusing, as i have little time to get used to it.

**Comment by el00ruobuob** [comment]
@erciccione isn't the files recurvisely links from kovri-docs? I think I remember @anonimal mentioning kovri-docs was the main resources to translate.

**Comment by Josexv1** [comment]
@el00ruobuob  is right, **kovri-docs/i18n** updates **kovri-site/kovri.i2p/_i18n** as stated in #73

**Comment by erciccione** [comment]
@el00ruobuob the content of the "docs" page on getkovri and most of the rest of the website is stored on kovri-site, but yes, now that i check them, some of those files are still a duplicate of the content of kovri-docs.

This is very confusing and i already asked in past to clarify which files have been ported to kovri-docs and which weren't. @rehrar @anonimal Guys, i really need a clarification here. I have to say the communication with me about kovri-related localizations has been very poor and almost not existent in the past months (talking about the localization of the website, not the README or other recent works). I really need to receive more instructions/updates from the Kovri team or i will end up asking our translators to work on something that will not being used or it's a duplicate.

it's not easy for me to follow the updates of every single monero-related project i take care of (they are about 8-9 at the moment), i really need a better communication from your side. @rehrar i remember i specifically spoke to you about this issue on `#monero-translations` long ago, this has been untouched for months and an issue was opened just recently (#73 ). Please let me know.

**Comment by Josexv1** [comment]
We need to have a meeting with translators that way we can create or edit the README with clear instructions, on which files to touch and what files are automatically created/updated for translators to work with. Actually when we clone the repo, we have these 2 folders with files. I'm using right now the **kovri-site/kovri.i2p/_i18n** for translation, so if things change i will switch to the **kovri-docs** repo.

**Comment by el00ruobuob** [comment]
@erciccione if we look at #62 or #61 it looks like we should update the docs from kovri-docs, and not from kovry-site. But @rehrar, @anonimal, or @oneiric should confirm.

**Comment by erciccione** [comment]
> looks like we should update the docs from kovri-docs, and not from kovry-site.

Yes, i'm aware of that. the problem is that it's not clear for me which part of monero-site should be translated except the .yml language files and which parts are duplicated/not used anymore

**Comment by anonimal** [comment]
```
2018-07-02 18:51:47     anonimal        Thanks erciccione_[m] you are amazing
2018-07-02 18:53:04     anonimal        https://github.com/monero-project/kovri-site/issues/73 really screwed the pooch for translators
2018-07-02 18:53:26     anonimal        I see josexv1 doing translation work on files that shouldn't exist in the kovri-site repo https://github.com/monero-project/kovri-site/issues/83#issuecomment-401540319
2018-07-02 18:53:56     anonimal        They are out of date, shouldn't be translated, and shouldn't exist in the repo.
2018-07-02 18:54:09     anonimal        I really hope rehrar returns to help clean this up
2018-07-02 18:55:26     anonimal        erciccione_[m]: priority is translating the kovri readme like you did. 2nd is making sure all non-english languages are translated exactly as seen in the english folder (new layout, new files). 3rdly, the website (because the website is supposed to pull from kovri-docs repo).
2018-07-02 18:55:44     anonimal        Does that make sense?
```

These comments apply to this issue too. @erciccione Yes, @rehrar really screwed the pooch here and I've not been maintaining the site because I'm busy with everything else. I propose the following:

1. 1st priority is translating the kovri readme in all languages, like you did, @erciccione.
2. 2nd is making sure all non-english languages in kovri-docs are translated exactly as seen in the english folder (new layout, new files) in the kovri-docs repo.
3. 3rdly, the website (because the website is supposed to pull from kovri-docs repo).

By the time the first 2 points are done, hopefully @rehrar will have returned to help clean this up.

**Comment by el00ruobuob** [comment]
Hanks @anonimal. Regarding 2:
> making sure all non-english languages in kovri-docs are translated exactly as seen in the english folder (new layout, new files) in the kovri-docs repo.
Does this mean we should clean up the directories? And only keep the exact same files?

**Comment by anonimal** [comment]
Yes.

**Comment by Josexv1** [comment]
I'm changing the translation details to kovri-docs. Will update the list on the other comment when i can.

**Comment by erciccione** [comment]
> 1st priority is translating the kovri readme in all languages, like you did, @erciccione.

OK, will geve instructions to start with this, then we will move to the second point. Thanks for the clarification @anonimal

**Comment by erciccione** [comment]
just opened monero-project/kovri-docs#59 @anonimal please merge ASAP so we can start working on point 1 of the list.

**Comment by anonimal** [comment]
Merged.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-site/issues/122 for details.
