### ISSUE TITLE
Docs sidebar block is not responsive.

### ISSUE THREAD

**Issue by Josexv1** [monero-project/kovri-site#84]
The block on the sidebar is not dynamically adjusting the size, so in some languages where the words are longer or shorter the sidebar will look disorted.

![sidebar](https://i.imgur.com/neVs3uT.jpg)

**Comment by rehrar** [comment]
This page will be deprecated soon.

**Comment by rehrar** [comment]
Docs page is now no longer on the website. This issue can be closed @anonimal
