### ISSUE TITLE
Update check.kovri.i2p

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-site#86]
That placeholder has been there for years now. We need to have something actually useful. At one point long ago I worked with @serhack and @rehrar on something related to #4. Is any of that work still around?

**Comment by serhack** [comment]
Pinging @rehrar , when you have time, try to contact me :) We can work together for this!

**Comment by rehrar** [comment]
Did I not give my portion of this work already to you @serhack ?

**Comment by anonimal** [comment]
This is resolved in #89 and #90.

**Comment by anonimal** [comment]
Referencing #79
